# Site settings
title: "Joel Laskow - Professional Page"
email: "joellaskow#gmail.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jlaskow.github.io"  # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
