# Site settings
title: "Joel Laskow"
email: "joellaskow@gmail.com"
description: "Test"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jlaskow.github.io"  # the base hostname & protocol for your site

LinkedIn: "www.linkedin.com/in/joel-laskow-10575b91" 
github: "https://github.com/jlaskow"

# Build settings
markdown: kramdown
